In [1]:
import numpy as np
import cv2
import pandas as pd

In [2]:
y_true = np.loadtxt('holes_locations.txt', delimiter=',')
y_pred = np.loadtxt('pred_circles.txt', delimiter=',')

In [3]:
len_y_pred = len(y_pred)
len_y_true = len(y_true)
num_found_holes = len_y_pred / len_y_true

In [4]:
y_pred_r = np.zeros(99)
for i in range(0, len_y_pred):
    list_distance = []
    for index in range(0, len_y_true):
        distance = np.sqrt(((y_pred[i][0] - y_true[index][0]) ** 2) + ((y_pred[i][1] - y_true[index][1]) ** 2))
        list_distance.append(distance)
    if min(list_distance) <= 50:  # d<10
        if y_pred_r[list_distance.index(min(list_distance))] == 0:
            y_pred_r[list_distance.index(min(list_distance))] = y_pred[i][2]
        else:
            smaller_r = min(y_pred_r[list_distance.index(min(list_distance))], y_pred[i][2])
            y_pred_r[list_distance.index(min(list_distance))] = smaller_r
            
            

In [5]:
y_true_r = []
for i in range(0, len_y_true):
    y_true_r.append(y_true[i][2])
y_true_r = np.array(y_true_r)
y_true_r

array([ 9.,  9.,  9.,  5.,  5.,  3., 10.,  3.,  9.,  5.,  2.,  7.,  7.,
        5.,  2.,  5.,  7.,  6.,  2.,  2.,  2., 10.,  7.,  3.,  2., 10.,
        2.,  7.,  7.,  2.,  3.,  3.,  2.,  5.,  3.,  3.,  3.,  7.,  2.,
        2.,  9.,  9.,  9.,  9.,  6.,  4.,  4., 10.,  9.,  4.,  5., 10.,
        7.,  3.,  3.,  3.,  5.,  9.,  7.,  5.,  9.,  3.,  3.,  5.,  7.,
        6.,  9.,  4.,  5.,  9.,  4.,  9.,  7.,  9.,  2.,  9.,  2.,  5.,
        3.,  3.,  3.,  3.,  3.,  5.,  5.,  6.,  7.,  5., 10.,  7.,  7.,
       10.,  9.,  3.,  3.,  9.,  7.,  7.,  2.])

In [6]:
y_pred_r

array([ 9.,  9., 10.,  5.,  6.,  4.,  9.,  4., 10.,  5.,  0.,  8.,  8.,
        5.,  2.,  6.,  7.,  8.,  2.,  0.,  0., 10.,  8.,  4.,  3., 10.,
        2.,  8.,  8.,  3.,  4.,  4.,  2.,  6.,  3.,  3.,  3.,  7.,  0.,
        0.,  9.,  8., 10.,  9.,  8.,  6.,  6.,  9., 10.,  6.,  6.,  9.,
        8.,  4.,  4.,  4.,  5., 10.,  8.,  6., 10.,  4.,  2.,  6.,  8.,
        7., 10.,  6.,  6., 10.,  6.,  9.,  8.,  9.,  2.,  9.,  0.,  6.,
        4.,  4.,  4.,  4.,  4.,  2.,  6.,  8.,  8.,  6., 10.,  7.,  8.,
        6.,  9.,  2.,  2., 10.,  8.,  8.,  3.])

In [41]:
y_pred_r = [10, 9 , 10, 5, 7 ,3, 99,99, 99,99,99,99,99,
                            99,99,99,7,8,3,2,3,10,7,3,2,9,
                            2, 7, 7, 2, 3, 3, 2, 5, 3, 3, 3, 7, 2,
                           2, 10, 9, 9, 9, 6,4, 4, 9, 9, 4, 5, 10,
                           7, 3, 3, 3, 5,9,7,5,9,2,3,5,7,
                           5,9,3,5,9,4,9,7,9,2,9,2,5,
                           3,3,2,2,3,5,5,7,7,5,10,7,7,
                           10,9,3,3,9,7,7,2]
y_pred_r = np.array(y_pred_r)

In [42]:
y_pred_r

array([10,  9, 10,  5,  7,  3, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,  7,
        8,  3,  2,  3, 10,  7,  3,  2,  9,  2,  7,  7,  2,  3,  3,  2,  5,
        3,  3,  3,  7,  2,  2, 10,  9,  9,  9,  6,  4,  4,  9,  9,  4,  5,
       10,  7,  3,  3,  3,  5,  9,  7,  5,  9,  2,  3,  5,  7,  5,  9,  3,
        5,  9,  4,  9,  7,  9,  2,  9,  2,  5,  3,  3,  2,  2,  3,  5,  5,
        7,  7,  5, 10,  7,  7, 10,  9,  3,  3,  9,  7,  7,  2])

In [7]:
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.metrics import mean_squared_error

In [14]:
false_found_holes = 0 / 94

In [15]:
false_found_holes #

0.0

In [8]:
num_found_holes # How many holes have been found

0.9494949494949495

In [9]:
mean_squared_error = mean_squared_error(y_true_r, y_pred_r)
mean_squared_error

1.393939393939394

In [10]:
mean_absolute_percentage_error = mean_absolute_percentage_error(y_true_r, y_pred_r)
mean_absolute_percentage_error

0.2333493666827